// function info(){
//     alert('using function')
// }

// info()


//!--using function in evenlistener
// let btn=document.getElementById('btn');
// btn.addEventListener('click', function info(){
//      alert('using function inside listener')
//  })

 //!--calling function in eventlistener using only function name 
// function info(){
//     alert('using function name without paranthesis')
// }

// btn.addEventListener('click',info)




